### ISSUE TITLE
Error decoding packet

### ISSUE THREAD

**Issue by paguos** [openfaas-incubator/kafka-connector#23]
Hi guys! I currently using the latest version of OpenFaaS and Kafka. I get the following message while trying to execute a function when a message arrives to the topic "faas-request": 

```consumer error:  kafka: error while consuming faas-request/0: kafka: error decoding packet: CRC didn't match expected 0x0 got 0xe38a6876```

Did anyone had that problem before? Thanks!

**Comment by alexellis** [comment]
Hi, I haven't seen this error, please can you fill out this template?

Alex



## Expected Behaviour



## Current Behaviour



## Possible Solution



## Steps to Reproduce (for bugs)


1.
2.
3.
4.

## Context



## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Kafka version:

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:
