### ISSUE TITLE
Issues with installing kafka-connector with microk8s

### ISSUE THREAD

**Issue by jscharber** [openfaas-incubator/kafka-connector#47]
When installing the kafka-connector on Ubuntu 18.04 VM I had two issues requiring workarounds:

1-Zookeeper failed to start due to a security constraint.  Upgrading to the latest image fixed the problem.
2-Deploying to the microk8s service failed as a result of "latest" being hardcoded in the build.sh

I also modified the build.sh and deploy.sh to use the local microk8s repository and made the option configurable via a new environment variable called REPO.
Steps to reproduce are here:
https://gist.github.com/jscharber/432b0d566258ce067acede4b4d350d6a
My patches are attached

[patch.txt](https://github.com/openfaas-incubator/kafka-connector/files/3347519/patch.txt)

**Comment by alexellis** [comment]
Hi @jscharber 

Thank you for your interest in the project and for creating your patch.

Our contribution process requires that you submit a PR via GitHub:

https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md

Please let us know if you have any questions about raising the PR.

In this issue please could you propose the changes you wish to make?

I should also note that as a rule we will avoid using the `latest` tag since it creates maintenance issues. If you would like to increment the version of any component, please do that using a release tag.

The helm chart will also need to be updated (if applicable) - https://github.com/openfaas/faas-netes/tree/master/chart/kafka-connector

Alex

**Comment by alexellis** [comment]
cc @martindekov

**Comment by martindekov** [comment]
Hey @jscharber, I see value in your proposal, we mainly use the script for Travic CI (someone correct me if I am wrong here), as the building process really requires two commands which are equivalent to executing the script, if you have context on Docker, you can just:

```
$ docker build . --tag myreponame/my-kafka-connector:0.0.1
$ docker push myreponame/my-kafka-connector:0.0.1
```

which slightly longer than:

```
$ export TAG=x.y.z
$ make build push
```

For which we can re-think of using the scripts for building.

Please open PR with your patch so we can review it through the normal process.

Regards,
Martin

**Comment by martindekov** [comment]
Also nice gist 👍

**Comment by alexellis** [comment]
Not sure what's happening with this issue? It seems inactive after 6 mo+/- so I'll close
